# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('temp', models.IntegerField(default=0.0)),
                ('humi', models.IntegerField(default=0.0)),
                ('ontime', models.IntegerField(default=0)),
                ('lred', models.IntegerField(default=0)),
                ('lgreen', models.IntegerField(default=0)),
                ('lblue', models.IntegerField(default=0)),
            ],
        ),
    ]
